title: dataelemental
description: Coding to data formats and querying.
show_downloads: false
theme: jekyll-theme-slate
markdown: GFM

plugins:
  - jemoji
  - jekyll-mermaid
  - jekyll-asciidoc
